version: '3.1'

services:
  watch_together_backend:
    build:
      context: backend
      dockerfile: Dockerfil.dev
    container_name: watch_together_backend
    restart: always
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env.dev

  watch_together_frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: watch_together_frontend
    depends_on:
      - watch_together_backend
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    env_file:
      - .env.dev

  watch_together_pgadmin4:
    image: dpage/pgadmin4
    container_name: watch_together_pgadmin4
    ports:
      - 5050:80
    env_file:
      - .env.dev
    depends_on:
      - watch_together_db

  redis:
    image: redis:7.2-rc2
    container_name: watch_together_redis
    ports:
      - 6379:6379

  watch_together_db:
    image: postgres
    container_name: watch_together_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.dev
